site_name: Aspaara Planning

#Github Repository Header
repo_name: Aspaara Planning
repo_url: https://github.com/besSejrani/react-coding-challenge

theme:
  #Language
  language: en

  # Use material styles
  name: material

  # Use custom logo and favicon
  logo: images/company/shortLogo.png
  favicon: images/company/shortLogo.png

  # Github Icon Header
  icon:
    repo: fontawesome/brands/github

  # Hide header
  features:
    - header.autohide

  # Color palettes
  palette:
    primary: black
    secondary: blue

# Extensionss
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true

# Footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/besSejrani

# Javascript
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
